# This file is auto-generated from the same code that generates
# https://docs.patreon.com. Community pull requests against this
# file may not be accepted.

require 'net/http'
require 'json'
require 'rack'
require 'net/http'
require 'json-api-vanilla'
require 'openssl'

require 'patreon/utils/jsonapi/url_util'
require 'patreon/utils/enum'
require 'patreon/utils/client'
require 'patreon/schemas/address'
require 'patreon/schemas/benefit'
require 'patreon/schemas/campaign'
require 'patreon/schemas/deliverable'
require 'patreon/schemas/goal'
require 'patreon/schemas/media'
require 'patreon/schemas/member'
require 'patreon/schemas/oauthclient'
require 'patreon/schemas/pledgeevent'
require 'patreon/schemas/post'
require 'patreon/schemas/tier'
require 'patreon/schemas/user'
require 'patreon/schemas/webhook'
require 'patreon/version'
require 'patreon/oauth'
require 'patreon/api'